#!/usr/bin/env php
<?php
namespace Aerc;

use Symfony\Component\Console\Application;

require __DIR__ . '/../vendor/autoload.php';

$app = new Application('Aer Console', '0.1');

$app->add(new SpeakCommand);

$app->run();