#!/usr/bin/env php
<?php
namespace Aer\Console;

use Symfony\Component\Console\Application;

require __DIR__ . '/../../vendor/autoload.php';

$app = new Application('Aer Console', '0.1');

$app->add(new SpeakCommand());
$app->add(new MakeMigrationCommand());
$app->add(new MakePackageCommand());
$app->add(new MigrateCommand());

$app->run();